// Date: 7/22/2014 12:06:27 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.letsmodreboot.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLocomotiveFrame extends ModelBase
{
	  //fields
    ModelRenderer Stack;
    ModelRenderer Dome;
    ModelRenderer MidBottomFrame;
    ModelRenderer LowerBoiler;
    ModelRenderer UpperBoiler;
    ModelRenderer LeftPiston;
    ModelRenderer LeftGuideBridge;
    ModelRenderer LeftPistonGuideUpper;
    ModelRenderer LeftPistonGuideLower;
    ModelRenderer RightPiston;
    ModelRenderer RightGuideBridge;
    ModelRenderer RightPistonGuideUpper;
    ModelRenderer RightPistonGuideLower;
    ModelRenderer PistonConnector;
  
  public ModelLocomotiveFrame()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Stack = new ModelRenderer(this, 76, 98);
      Stack.addBox(-2F, -17F, -13F, 4, 3, 4);
      Stack.setRotationPoint(0F, -1F, 0F);
      Stack.setTextureSize(64, 32);
      Stack.mirror = true;
      setRotation(Stack, 0F, 0F, 0F);
      Dome = new ModelRenderer(this, 52, 98);
      Dome.addBox(-3F, -16F, -3F, 6, 2, 6);
      Dome.setRotationPoint(0F, -1F, 0F);
      Dome.setTextureSize(64, 32);
      Dome.mirror = true;
      setRotation(Dome, 0F, 0F, 0F);
      MidBottomFrame = new ModelRenderer(this, 0, 0);
      MidBottomFrame.addBox(-4F, -10F, -8F, 8, 10, 16);
      MidBottomFrame.setRotationPoint(0F, -1F, 0F);
      MidBottomFrame.setTextureSize(64, 32);
      MidBottomFrame.mirror = true;
      setRotation(MidBottomFrame, 0F, 0F, 0F);
      LowerBoiler = new ModelRenderer(this, 50, 0);
      LowerBoiler.addBox(-3F, -10F, -16F, 6, 6, 27);
      LowerBoiler.setRotationPoint(0F, -1F, 0F);
      LowerBoiler.setTextureSize(64, 32);
      LowerBoiler.mirror = true;
      setRotation(LowerBoiler, 0F, 0F, 0F);
      UpperBoiler = new ModelRenderer(this, 0, 66);
      UpperBoiler.addBox(-8F, -15F, -16F, 16, 5, 27);
      UpperBoiler.setRotationPoint(0F, -1F, 0F);
      UpperBoiler.setTextureSize(64, 32);
      UpperBoiler.mirror = true;
      setRotation(UpperBoiler, 0F, 0F, 0F);
      LeftPiston = new ModelRenderer(this, 32, 98);
      LeftPiston.addBox(-9F, -8F, -17F, 5, 7, 5);
      LeftPiston.setRotationPoint(0F, -1F, 0F);
      LeftPiston.setTextureSize(64, 32);
      LeftPiston.mirror = true;
      setRotation(LeftPiston, 0F, 0F, 0F);
      LeftGuideBridge = new ModelRenderer(this, 18, 114);
      LeftGuideBridge.addBox(8F, -7F, -5F, 1, 5, 1);
      LeftGuideBridge.setRotationPoint(0F, -1F, 0F);
      LeftGuideBridge.setTextureSize(64, 32);
      LeftGuideBridge.mirror = true;
      setRotation(LeftGuideBridge, 0F, 0F, 0F);
      LeftPistonGuideUpper = new ModelRenderer(this, 0, 114);
      LeftPistonGuideUpper.addBox(7F, -7F, -12F, 1, 1, 8);
      LeftPistonGuideUpper.setRotationPoint(0F, -1F, 0F);
      LeftPistonGuideUpper.setTextureSize(64, 32);
      LeftPistonGuideUpper.mirror = true;
      setRotation(LeftPistonGuideUpper, 0F, 0F, 0F);
      LeftPistonGuideLower = new ModelRenderer(this, 0, 114);
      LeftPistonGuideLower.addBox(7F, -3F, -12F, 1, 1, 8);
      LeftPistonGuideLower.setRotationPoint(0F, -1F, 0F);
      LeftPistonGuideLower.setTextureSize(64, 32);
      LeftPistonGuideLower.mirror = true;
      setRotation(LeftPistonGuideLower, 0F, 0F, 0F);
      RightPiston = new ModelRenderer(this, 32, 98);
      RightPiston.addBox(4F, -8F, -17F, 5, 7, 5);
      RightPiston.setRotationPoint(0F, -1F, 0F);
      RightPiston.setTextureSize(64, 32);
      RightPiston.mirror = true;
      setRotation(RightPiston, 0F, 0F, 0F);
      RightGuideBridge = new ModelRenderer(this, 18, 114);
      RightGuideBridge.addBox(-9F, -7F, -5F, 1, 5, 1);
      RightGuideBridge.setRotationPoint(0F, -1F, 0F);
      RightGuideBridge.setTextureSize(64, 32);
      RightGuideBridge.mirror = true;
      setRotation(RightGuideBridge, 0F, 0F, 0F);
      RightPistonGuideUpper = new ModelRenderer(this, 0, 114);
      RightPistonGuideUpper.addBox(-8F, -7F, -12F, 1, 1, 8);
      RightPistonGuideUpper.setRotationPoint(0F, -1F, 0F);
      RightPistonGuideUpper.setTextureSize(64, 32);
      RightPistonGuideUpper.mirror = true;
      setRotation(RightPistonGuideUpper, 0F, 0F, 0F);
      RightPistonGuideLower = new ModelRenderer(this, 0, 114);
      RightPistonGuideLower.addBox(-8F, -3F, -12F, 1, 1, 8);
      RightPistonGuideLower.setRotationPoint(0F, -1F, 0F);
      RightPistonGuideLower.setTextureSize(64, 32);
      RightPistonGuideLower.mirror = true;
      setRotation(RightPistonGuideLower, 0F, 0F, 0F);
      PistonConnector = new ModelRenderer(this, 28, 52);
      PistonConnector.addBox(-4F, -8F, -16F, 8, 2, 4);
      PistonConnector.setRotationPoint(0F, -1F, 0F);
      PistonConnector.setTextureSize(64, 32);
      PistonConnector.mirror = true;
      setRotation(PistonConnector, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Stack.render(f5);
    Dome.render(f5);
    MidBottomFrame.render(f5);
    LowerBoiler.render(f5);
    UpperBoiler.render(f5);
    LeftPiston.render(f5);
    LeftGuideBridge.render(f5);
    LeftPistonGuideUpper.render(f5);
    LeftPistonGuideLower.render(f5);
    RightPiston.render(f5);
    RightGuideBridge.render(f5);
    RightPistonGuideUpper.render(f5);
    RightPistonGuideLower.render(f5);
    PistonConnector.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
