// Date: 7/25/2014 9:44:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.letsmodreboot.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLocomotiveWheel extends ModelBase
{
  //fields
    ModelRenderer FRWRCenter;
    ModelRenderer FRWRTall;
    ModelRenderer FRWRWide;
    ModelRenderer FRWFTall;
    ModelRenderer FRWFWide;
    ModelRenderer FRWFRim1;
    ModelRenderer FRWFRim2;
    ModelRenderer FRWFRim3;
    ModelRenderer FRWFRim4;
    ModelRenderer FRWFRim5;
    ModelRenderer FRWFRim6;
    ModelRenderer FRWFRim7;
    ModelRenderer FLWRCenter;
    ModelRenderer FLWRTall;
    ModelRenderer FLWRWide;
    ModelRenderer FLWFTall;
    ModelRenderer FLWFWide;
    ModelRenderer FLWFRim1;
    ModelRenderer FLWFRim2;
    ModelRenderer FLWFRim3;
    ModelRenderer FLWFRim4;
    ModelRenderer FLWFRim5;
    ModelRenderer FLWFRim6;
    ModelRenderer FLWFRim7;
  
  public ModelLocomotiveWheel()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      FRWRCenter = new ModelRenderer(this, 0, 26);
      FRWRCenter.addBox(-1F, -4F, -4F, 1, 8, 8);
      FRWRCenter.setRotationPoint(-4F, 0F, 0F);
      FRWRCenter.setTextureSize(64, 32);
      FRWRCenter.mirror = true;
      setRotation(FRWRCenter, 0F, 0F, 0F);
      FRWRTall = new ModelRenderer(this, 18, 26);
      FRWRTall.addBox(-1F, -5F, -2F, 1, 10, 4);
      FRWRTall.setRotationPoint(-4F, 0F, 0F);
      FRWRTall.setTextureSize(64, 32);
      FRWRTall.mirror = true;
      setRotation(FRWRTall, 0F, 0F, 0F);
      FRWRWide = new ModelRenderer(this, 28, 26);
      FRWRWide.addBox(-1F, -2F, -5F, 1, 4, 10);
      FRWRWide.setRotationPoint(-4F, 0F, 0F);
      FRWRWide.setTextureSize(64, 32);
      FRWRWide.mirror = true;
      setRotation(FRWRWide, 0F, 0F, 0F);
      FRWFTall = new ModelRenderer(this, 0, 42);
      FRWFTall.addBox(-2F, -4F, -1F, 1, 1, 2);
      FRWFTall.setRotationPoint(-4F, 0F, 0F);
      FRWFTall.setTextureSize(64, 32);
      FRWFTall.mirror = true;
      setRotation(FRWFTall, 0F, 0F, 0F);
      FRWFWide = new ModelRenderer(this, 6, 42);
      FRWFWide.addBox(-2F, -3F, -3F, 1, 3, 6);
      FRWFWide.setRotationPoint(-4F, 0F, 0F);
      FRWFWide.setTextureSize(64, 32);
      FRWFWide.mirror = true;
      setRotation(FRWFWide, 0F, 0F, 0F);
      FRWFRim1 = new ModelRenderer(this, 20, 42);
      FRWFRim1.addBox(-2F, -1F, 2F, 1, 2, 2);
      FRWFRim1.setRotationPoint(-4F, 0F, 0F);
      FRWFRim1.setTextureSize(64, 32);
      FRWFRim1.mirror = true;
      setRotation(FRWFRim1, 0F, 0F, 0F);
      FRWFRim2 = new ModelRenderer(this, 26, 42);
      FRWFRim2.addBox(-2F, -1F, -4F, 1, 2, 2);
      FRWFRim2.setRotationPoint(-4F, 0F, 0F);
      FRWFRim2.setTextureSize(64, 32);
      FRWFRim2.mirror = true;
      setRotation(FRWFRim2, 0F, 0F, 0F);
      FRWFRim3 = new ModelRenderer(this, 20, 46);
      FRWFRim3.addBox(-2F, 1F, 2F, 1, 2, 1);
      FRWFRim3.setRotationPoint(-4F, 0F, 0F);
      FRWFRim3.setTextureSize(64, 32);
      FRWFRim3.mirror = true;
      setRotation(FRWFRim3, 0F, 0F, 0F);
      FRWFRim4 = new ModelRenderer(this, 24, 46);
      FRWFRim4.addBox(-2F, 1F, -3F, 1, 2, 1);
      FRWFRim4.setRotationPoint(-4F, 0F, 0F);
      FRWFRim4.setTextureSize(64, 32);
      FRWFRim4.mirror = true;
      setRotation(FRWFRim4, 0F, 0F, 0F);
      FRWFRim5 = new ModelRenderer(this, 32, 42);
      FRWFRim5.addBox(-2F, 2F, -2F, 1, 1, 4);
      FRWFRim5.setRotationPoint(-4F, 0F, 0F);
      FRWFRim5.setTextureSize(64, 32);
      FRWFRim5.mirror = true;
      setRotation(FRWFRim5, 0F, 0F, 0F);
      FRWFRim6 = new ModelRenderer(this, 0, 49);
      FRWFRim6.addBox(-2F, 3F, -1F, 1, 1, 2);
      FRWFRim6.setRotationPoint(-4F, 0F, 0F);
      FRWFRim6.setTextureSize(64, 32);
      FRWFRim6.mirror = true;
      setRotation(FRWFRim6, 0F, 0F, 0F);
      FRWFRim7 = new ModelRenderer(this, 0, 49);
      FRWFRim7.addBox(-2F, 1F, -1F, 1, 1, 2);
      FRWFRim7.setRotationPoint(-4F, 0F, 0F);
      FRWFRim7.setTextureSize(64, 32);
      FRWFRim7.mirror = true;
      setRotation(FRWFRim7, 0F, 0F, 0F);
      FLWRCenter = new ModelRenderer(this, 0, 26);
      FLWRCenter.addBox(0F, -4F, -4F, 1, 8, 8);
      FLWRCenter.setRotationPoint(4F, 0F, 0F);
      FLWRCenter.setTextureSize(64, 32);
      FLWRCenter.mirror = true;
      setRotation(FLWRCenter, -1.570796F, 0F, 0F);
      FLWRTall = new ModelRenderer(this, 18, 26);
      FLWRTall.addBox(0F, -5F, -2F, 1, 10, 4);
      FLWRTall.setRotationPoint(4F, 0F, 0F);
      FLWRTall.setTextureSize(64, 32);
      FLWRTall.mirror = true;
      setRotation(FLWRTall, -1.570796F, 0F, 0F);
      FLWRWide = new ModelRenderer(this, 28, 26);
      FLWRWide.addBox(0F, -2F, -5F, 1, 4, 10);
      FLWRWide.setRotationPoint(4F, 0F, 0F);
      FLWRWide.setTextureSize(64, 32);
      FLWRWide.mirror = true;
      setRotation(FLWRWide, -1.570796F, 0F, 0F);
      FLWFTall = new ModelRenderer(this, 0, 42);
      FLWFTall.addBox(1F, -4F, -1F, 1, 1, 2);
      FLWFTall.setRotationPoint(4F, 0F, 0F);
      FLWFTall.setTextureSize(64, 32);
      FLWFTall.mirror = true;
      setRotation(FLWFTall, -1.570796F, 0F, 0F);
      FLWFWide = new ModelRenderer(this, 6, 42);
      FLWFWide.addBox(1F, -3F, -3F, 1, 3, 6);
      FLWFWide.setRotationPoint(4F, 0F, 0F);
      FLWFWide.setTextureSize(64, 32);
      FLWFWide.mirror = true;
      setRotation(FLWFWide, -1.570796F, 0F, 0F);
      FLWFRim1 = new ModelRenderer(this, 20, 42);
      FLWFRim1.addBox(1F, -1F, -4F, 1, 2, 2);
      FLWFRim1.setRotationPoint(4F, 0F, 0F);
      FLWFRim1.setTextureSize(64, 32);
      FLWFRim1.mirror = true;
      setRotation(FLWFRim1, -1.570796F, 0F, 0F);
      FLWFRim2 = new ModelRenderer(this, 26, 42);
      FLWFRim2.addBox(1F, -1F, 2F, 1, 2, 2);
      FLWFRim2.setRotationPoint(4F, 0F, 0F);
      FLWFRim2.setTextureSize(64, 32);
      FLWFRim2.mirror = true;
      setRotation(FLWFRim2, -1.570796F, 0F, 0F);
      FLWFRim3 = new ModelRenderer(this, 20, 46);
      FLWFRim3.addBox(1F, 1F, -3F, 1, 2, 1);
      FLWFRim3.setRotationPoint(4F, 0F, 0F);
      FLWFRim3.setTextureSize(64, 32);
      FLWFRim3.mirror = true;
      setRotation(FLWFRim3, -1.570796F, 0F, 0F);
      FLWFRim4 = new ModelRenderer(this, 24, 46);
      FLWFRim4.addBox(1F, 1F, 2F, 1, 2, 1);
      FLWFRim4.setRotationPoint(4F, 0F, 0F);
      FLWFRim4.setTextureSize(64, 32);
      FLWFRim4.mirror = true;
      setRotation(FLWFRim4, -1.570796F, 0F, 0F);
      FLWFRim5 = new ModelRenderer(this, 32, 42);
      FLWFRim5.addBox(1F, 2F, -2F, 1, 1, 4);
      FLWFRim5.setRotationPoint(4F, 0F, 0F);
      FLWFRim5.setTextureSize(64, 32);
      FLWFRim5.mirror = true;
      setRotation(FLWFRim5, -1.570796F, 0F, 0F);
      FLWFRim6 = new ModelRenderer(this, 0, 49);
      FLWFRim6.addBox(1F, 3F, -1F, 1, 1, 2);
      FLWFRim6.setRotationPoint(4F, 0F, 0F);
      FLWFRim6.setTextureSize(64, 32);
      FLWFRim6.mirror = true;
      setRotation(FLWFRim6, -1.570796F, 0F, 0F);
      FLWFRim7 = new ModelRenderer(this, 0, 49);
      FLWFRim7.addBox(1F, 1F, -1F, 1, 1, 2);
      FLWFRim7.setRotationPoint(4F, 0F, 0F);
      FLWFRim7.setTextureSize(64, 32);
      FLWFRim7.mirror = true;
      setRotation(FLWFRim7, -1.570796F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FRWRCenter.render(f5);
    FRWRTall.render(f5);
    FRWRWide.render(f5);
    FRWFTall.render(f5);
    FRWFWide.render(f5);
    FRWFRim1.render(f5);
    FRWFRim2.render(f5);
    FRWFRim3.render(f5);
    FRWFRim4.render(f5);
    FRWFRim5.render(f5);
    FRWFRim6.render(f5);
    FRWFRim7.render(f5);
    FLWRCenter.render(f5);
    FLWRTall.render(f5);
    FLWRWide.render(f5);
    FLWFTall.render(f5);
    FLWFWide.render(f5);
    FLWFRim1.render(f5);
    FLWFRim2.render(f5);
    FLWFRim3.render(f5);
    FLWFRim4.render(f5);
    FLWFRim5.render(f5);
    FLWFRim6.render(f5);
    FLWFRim7.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}